# FlatOut UC Half-Life Movement by Chloe @gaycoderprincess
# enjoy, nya~ :3

[main]
enabled=true
longjump=false
autohop=true
abh=false
abh_mixed=false
bhop_cap=false
better_maxvelocity=false
noclip_toggle=false

[game]
teleport_car=false
car_godmode=false

[advanced]
physics_steps=4
collision_density=2

[cvars]
fov_desired=90
sensitivity=1
volume=1
cl_bob=0.01
cl_bobcycle=0.8
cl_bobup=0.5
cl_forwardspeed=400
cl_sidespeed=400
cl_upspeed=320
cl_movespeedkey=0.3
sv_gravity=800
sv_stopspeed=100
sv_maxspeed=320
sv_noclipspeed=320
sv_accelerate=10
sv_airaccelerate=10
sv_wateraccelerate=10
sv_friction=4
sv_edgefriction=2
sv_waterfriction=1
#sv_entgravity=1.0
sv_bounce=1.0
sv_stepsize=18
sv_maxvelocity=2000
#mp_footsteps=true
sv_rollangle=2
sv_rollspeed=200